PUT http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLWFwaSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzAwMjQ0MjkyfQ.-QCPcpjYG9WGGAyT2CHno86kPwkwrja7kKXejtyVDx4

{
  "id": "6d1af506-76eb-4f96-8d7f-d5cf75af3068",
  "birthDate": "2001-04-25",
  "description": "Elton é um cara legal.",
  "name": "Elton Henrique de Oliveira",
  "userName": "elton",
  "role": "super",
  "contacts": [
    {
      "label": "47996330692",
      "type": {
        "uuid": "361bf37e-9754-4ef4-bce3-c11f67ea9aa4"
      }
    },
    {
      "label": "elton.h.oli@gmail.com",
      "type": {
        "uuid": "e2c2e70c-29d0-4f47-85da-04ed2ebdf53a"
      }
    }
  ]
}
