PUT http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLWFwaSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzAwMDk3MTIxfQ.yyP2SWZGHh1QLfm8CyddoMY-5AORIHVObTNg2BeXS9Y

{
  "id": "ba45c62e-26b1-42cc-b380-a3496fb066c3",
  "birthDate": "2001-04-25",
  "description": "Elton é um cara legal.",
  "email": "elton.h.oli@gmail.com",
  "name": "Elton Henrique de Oliveira",
  "username": "elton",
  "role": "SUPER",
  "contacts": [
    {
      "label": "47996330692",
      "type": null
    },
    {
      "label": "facebook",
      "type": null
    }
  ]
}
